version: '3.9'

services:

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: cliq_app_db

  server:
    build:
      context: .
    # command: bash -c "scripts/setupServer.sh && chmod +x scripts/runServer.sh && scripts/runServer.sh"
    command: bash -c "pwd"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    container_name: cliq_app_server

    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
