version: '3.9'

services:

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5432"
    restart: on-failure
    # command: bash -c "echo ${DB_NAME}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: cliq_app_db
    # command: -p 5433

  server:
    build:
      context: .
    command: bash -c "scripts/setupServer.sh && chmod +x scripts/runServer.sh && scripts/runServer.sh"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    container_name: cliq_app_server

    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
