# Generated by Django 4.0.2 on 2023-09-04 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('duration', models.CharField(max_length=50, verbose_name='title')),
                ('release_year', models.IntegerField(verbose_name='release year')),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('DRAMA', 'Drama')], max_length=10, verbose_name='genre')),
                ('streaming_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Netflix', 'Netflix'), ('Max', 'Max'), ('Hulu', 'Hulu'), ('Peacock', 'Peacock'), ('Disney+', 'Disney Plus'), ('Primer', 'Prime')], max_length=20), blank=True, default=list, size=6, verbose_name='streaming options')),
            ],
        ),
    ]
