# Generated by Django 4.0.2 on 2023-09-04 18:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Drama', 'Drama'), ('Other', 'Other')], max_length=20), blank=True, default=list, size=5, verbose_name='genre'),
        ),
    ]
