# Generated by Django 4.0.2 on 2023-09-04 18:45

import app.movie.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Drama', 'Drama'), ('Other', 'Other')], max_length=20), default=app.movie.models.default_genres, size=5, verbose_name='genre'),
        ),
    ]
