# Generated by Django 4.0.2 on 2023-09-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_remove_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=90, verbose_name='duration'),
            preserve_default=False,
        ),
    ]
