# Generated by Django 4.0.2 on 2023-08-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=50, null=True, verbose_name='Last Name')),
            ],
        ),
    ]
