# Generated by Django 4.0.2 on 2023-08-25 16:28

import app.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.users.managers.UserManager()),
            ],
        ),
    ]
