# Generated by Django 4.0.2 on 2023-08-30 01:38

import app.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.users.managers.UserManager()),
            ],
        ),
    ]
