# Generated by Django 4.0.2 on 2023-09-01 05:20

import app.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_email_address_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=app.users.utils.generate_user_identifier, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='ids'),
        ),
    ]
